# CSCI 184 Homework #1
## Patrick Callahan, Arjun Chimni, Andrew Schulz
## One-Hot Encoding

## 1. Load the dataset from ‘train.csv’ into a pandas DataFrame and print it along with its shape.

In [99]:
import pandas as pd
import csv

train_data = pd.read_csv('train.csv') #Loading dataset
train_data_df = pd.DataFrame(train_data) #Loading csv into dataframe
train_data_df #printing the DataFrame

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## 2. For dealing with missing values, delete a column with any Null value (Note: not recommended approach, but here focus is one-hot encoding). Also delete the ‘ID’ column.

In [100]:
#check to see what columns have null values. If they do have null value, delete the column
for value in train_data_df:
    if train_data_df[value].isnull().sum() > 0: #if the there exists at least 1 null value
        print(value, ' : ', train_data_df[value].isnull().sum()) #print the column name and the amount of null values
        del train_data_df[value]

LotFrontage  :  259
Alley  :  1369
MasVnrType  :  8
MasVnrArea  :  8
BsmtQual  :  37
BsmtCond  :  37
BsmtExposure  :  38
BsmtFinType1  :  37
BsmtFinType2  :  38
Electrical  :  1
FireplaceQu  :  690
GarageType  :  81
GarageYrBlt  :  81
GarageFinish  :  81
GarageQual  :  81
GarageCond  :  81
PoolQC  :  1453
Fence  :  1179
MiscFeature  :  1406

In [101]:
#Check to make sure the columns were deleted. 
for value in train_data_df:
    if train_data_df[value].isnull().sum() > 0: #if the there exists at least 1 null value
        print(value, ' : ', train_data_df[value].isnull().sum()) #print the column name and the amount of null values
print("Check complete, there are no columns now with null values")

Check complete, there are no columns now with null values

In [102]:
# Print the data frame
del train_data_df['Id'] #deleting the Id column
train_data_df

,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,...,0,0,0,0,0,6,2008,WD,Normal,147500

## 3. For simplicity, we will work with all the numerical columns but just a subset of the categorical columns. Among all the remaining categorical columns after step 2, choose the categorical columns that have less than 10 unique values.

In [103]:
# Go through the dataframe. If the type of the column is categorical, count the amount of unique values. 
# If the value of unique values is greater than 10, delete the column from the dataframe.  
for column in train_data_df: 
    if train_data_df[column].dtype != int: #if the data is not an integer value (meaning it is categorical)
        unique = len(pd.unique(train_data_df[column])) #find the count of unique values in the column
        if unique > 10: #if the count of unique is less than 10
            del train_data_df[column] #delete the column

## 4. Print the resultant dataframe and its shape after step 3.

In [104]:
train_data_df

,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Condition1,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Feedr,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Norm,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,Norm,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,Norm,...,0,0,0,0,0,6,2008,WD,Normal,147500

## 5. Divide the data into X and Y, where X is the set of features and Y is the target variable. For this dataset the ‘SalePrice’ is the target variable.

## 6. For step 5, two approaches will be used (as discussed in class):
- a. Set of ONLY numerical features and dropping all Categorical features
- b. Set of features comprising both numerical and one-hot encoded categorical features.

In [105]:
from sklearn.preprocessing import OneHotEncoder
# first, initialize the target value: 
target = train_data_df['SalePrice']
del train_data_df['SalePrice']
# initialize only numerical features dataframe:
num_only_df = pd.DataFrame()
for column in train_data_df:
    if train_data_df[column].dtype == int: #if the column value is numerical
        num_only_df[column] = train_data_df[column] 

num_only_df

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,60,8450,7,5,2003,2003,706,0,150,856,...,548,0,61,0,0,0,0,0,2,2008
1,20,9600,6,8,1976,1976,978,0,284,1262,...,460,298,0,0,0,0,0,0,5,2007
2,60,11250,7,5,2001,2002,486,0,434,920,...,608,0,42,0,0,0,0,0,9,2008
3,70,9550,7,5,1915,1970,216,0,540,756,...,642,0,35,272,0,0,0,0,2,2006
4,60,14260,8,5,2000,2000,655,0,490,1145,...,836,192,84,0,0,0,0,0,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,7917,6,5,1999,2000,0,0,953,953,...,460,0,40,0,0,0,0,0,8,2007
1456,20,13175,6,6,1978,1988,790,163,589,1542,...,500,349,0,0,0,0,0,0,2,2010
1457,70,9042,7,9,1941,2006,275,0,877,1152,...,252,0,60,0,0,0,0,2500,5,2010
1458,20,9717,5,6,1950,1996,49,1029,0,1078,...,240,366,0,112,0,0,0,0,4,2010
1459,20,9937,5,6,1965,1965,830,290,136,1256,...,276,736,68,0,0,0,0,0,6,2008

In [106]:
import numpy as np
# now do one hot encoding on categorical data
final_one_hot = pd.DataFrame() #initialize empty data set
for column in train_data_df:
    if train_data_df[column].dtype != int: #if the column value is categorical
        column_type = train_data_df[column] #take the name of the column
        column_df = pd.DataFrame(column_type, columns=[column]) #create a new dataframe for the one hot encoding of categorical data
        enc_df = pd.get_dummies(column_df, prefix=[column+'_']) # make a new dataframe with one hot encoding of the categorical variable with new column names
        column_df = column_df.join(enc_df) # join the two new dataframes
        del column_df[column] #delete the categorical column
        final_one_hot = pd.concat([final_one_hot, column_df], axis=1) #add the one hot encoding values to the final data frame

final_one_hot #print the data frame to show it worked.

,MSZoning__C (all),MSZoning__FV,MSZoning__RH,MSZoning__RL,MSZoning__RM,Street__Grvl,Street__Pave,LotShape__IR1,LotShape__IR2,LotShape__IR3,...,SaleType__ConLw,SaleType__New,SaleType__Oth,SaleType__WD,SaleCondition__Abnorml,SaleCondition__AdjLand,SaleCondition__Alloca,SaleCondition__Family,SaleCondition__Normal,SaleCondition__Partial
0,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1457,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1458,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1459,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0

## 7. Print the original dataframe joined with the one-hot encoded columns.

In [107]:
num_onehot_df = pd.DataFrame() # initialize a new final dataframe with one hot encoded columns joined with numerical
num_onehot_df = pd.concat([num_only_df, final_one_hot], axis=1) #join them
num_onehot_df #print the combined

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,SaleType__ConLw,SaleType__New,SaleType__Oth,SaleType__WD,SaleCondition__Abnorml,SaleCondition__AdjLand,SaleCondition__Alloca,SaleCondition__Family,SaleCondition__Normal,SaleCondition__Partial
0,60,8450,7,5,2003,2003,706,0,150,856,...,0,0,0,1,0,0,0,0,1,0
1,20,9600,6,8,1976,1976,978,0,284,1262,...,0,0,0,1,0,0,0,0,1,0
2,60,11250,7,5,2001,2002,486,0,434,920,...,0,0,0,1,0,0,0,0,1,0
3,70,9550,7,5,1915,1970,216,0,540,756,...,0,0,0,1,1,0,0,0,0,0
4,60,14260,8,5,2000,2000,655,0,490,1145,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,7917,6,5,1999,2000,0,0,953,953,...,0,0,0,1,0,0,0,0,1,0
1456,20,13175,6,6,1978,1988,790,163,589,1542,...,0,0,0,1,0,0,0,0,1,0
1457,70,9042,7,9,1941,2006,275,0,877,1152,...,0,0,0,1,0,0,0,0,1,0
1458,20,9717,5,6,1950,1996,49,1029,0,1078,...,0,0,0,1,0,0,0,0,1,0
1459,20,9937,5,6,1965,1965,830,290,136,1256,...,0,0,0,1,0,0,0,0,1,0

## 8. Once, the two sets of features are obtained from step 6, train a simple Linear Regression model from sklearn and obtain the Mean Absolute Error for both the cases:
- a. Mean Absolute Error when Dropping Categoricals:
- b. Mean Absolute Error with One-Hot Encoding

In [108]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

X = num_only_df
Y = target

X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

model = LinearRegression()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
print("Mean Absolute Error when Dropping Categoricals: ",metrics.mean_absolute_error(Y_test, Y_pred))

Mean Absolute Error when Dropping Categoricals:  22714.8946238551

In [109]:
X = num_onehot_df
Y = target

X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

model = LinearRegression()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
print("Mean Absolute Error with One-Hot Encoding: ",metrics.mean_absolute_error(Y_test, Y_pred))

Mean Absolute Error with One-Hot Encoding:  19636.40603060939